### ISSUE TITLE
Dynamic bridging

### ISSUE THREAD

**Issue by Surabhi-Sharma79** [Tifaifai/mosquitto#2]
Hello,
We used the code of **branch: master** for dynamic bridging using 
$SYS topic - 
$SYS/broker/bridge/new
But we are not sure as to what to send as payload for bridging configuration setup. 
We sent this payload
`connection bridge-pub address 172.16.55.1 topic TEST/TIME1 in out`
but the dynamic bridging setup did not work. Please help us out. We are waiting for a positive response.

**Comment by Tifaifai** [comment]
You can clone a new branch : Bridge-Dynamic_1.6.9
This is the last version !
THX

**Comment by kaedwen** [comment]
I have build the branch `Bridge-Dynamic_1.6.9` but adding a bridge with mosquitto_bridge nor with a publish does work. I have monitored `'$SYS/broker/bridge/#'` but there's nothing. Any ideas?

**Comment by Tifaifai** [comment]
@Surabhi-Sharma79
if you use mosquitto_pub, an example : 
```
# mosquitto_pub -h 172.16.55.1 -p 1883 -t '$SYS/broker/bridge/new' -m 'connection bridge-pub
address 172.16.55.1:1884
topic # both 0 TEST/TIME1 TEST/TIME2
'
```

**Comment by Tifaifai** [comment]
@hei-pa : 
I have commit an update for readme.md 
Section -> To dynamically create/delete/show a bridge, use:
`
mosquitto_bridge -p 1883 -c testBridge -a 127.0.0.1 -R 1884 -n -t # -q 0 -l test/1883/ -r test/1884/ -D both
`

**Comment by kaedwen** [comment]
thank you for your quick response but -k does not print anything

```
root@mosq1:/opt/bridge/mosquitto# mosquitto_bridge -c test -a 10.0.3.102 -R 1883 -n -t \# -q 0 -l local/ -r remote/ -D both              
Message New Bridge : connection test
address 10.0.3.102:1883
topic # both 0 local/ remote/
root@mosq1:/opt/bridge/mosquitto# mosquitto_bridge -k

```

I have build your branch and started the `mosquitto` binary from that build ... mosq1 running on lxc 10.0.3.101 and mosq2 running on lxc 10.0.3.102 ... both are pingable from each other

**Comment by Tifaifai** [comment]
`# mosquitto_bridge -h 127.0.0.1 -p 1883 -k
`

**Comment by kaedwen** [comment]
No I have seen the opening connection in the mosquitto log from 
```
mosquitto_bridge -k
```
and with the ip given the same result
```
root@mosq1:/opt/bridge/mosquitto# mosquitto_bridge -h 127.0.0.1 -p 1883 -k


```

**Comment by Tifaifai** [comment]
`mosquitto_bridge -h 10.0.3.101 -p 1883 -k`

**Comment by kaedwen** [comment]
`mosq1` is `10.0.3.101` so i am on that machine
```
root@mosq1:/opt/bridge/mosquitto# mosquitto_bridge -h 10.0.3.101 -p 1883 -k

```
nothing

**Comment by kaedwen** [comment]
I thought that subscribing to `'$SYS/broker/bridge/#'` should show somthing on `10.0.3.101` am I wrong?

**Comment by kaedwen** [comment]
```
  **************
  *    mosq1   *
  * 10.0.3.101 *
  **************
  
  **************
  *    mosq2   *
  * 10.0.3.102 *
  **************
  
  # Running this
  mosquitto_bridge -h 10.0.3.101 -p 1883 -c test -a 10.0.3.102 -R 1883 -n -t \# -q 0 -l local/ -r remote/ -D both 
  
  # Should forward all publishs to mosq1 with topic local/ to mosq2 remote/
  mosquitto_sub -h 10.0.3.101 -p 1883 -v -t "#"
  -> local/test hallo
  
  mosquitto_sub -h 10.0.3.102 -p 1883 -v -t "#"
  -> nothing
  
  # Publish something
  mosquitto_pub -h 10.0.3.101 -p 1883 -t "local/test" -m "hallo"
```

**Comment by Tifaifai** [comment]
Have you set allow_sys_update in your mosquitto configuration ??

```
# Config file for mosquitto : mosquitto_1883.conf


# =================================================================
# Default listener
# =================================================================
port 1883
http_dir /usr/local/etc/mqttb

# =================================================================
# Logging
# =================================================================
log_dest file /home/RPi/MQTT/light_1883.log
log_type all

# =================================================================
# Bridges
# =================================================================
connection tif
address 127.0.0.1:1884
topic # both 0 t/1883/ t/1884/

# If allow_sys_update is set to true, Mosquitto allows to interpret some $SYS
# topics. Interpreted topics are : $SYS/broker/bridge/new and
# $SYS/broker/bridge/del. They are used for dynamic bridges behaviour.
allow_sys_update true
```

**Comment by kaedwen** [comment]
Yeeehaa yes `allow_sys_update true` was missing because I have used the `mosquitto` binary without any config so the default seems to be `false`
