### ISSUE TITLE
binaries available?

### ISSUE THREAD

**Issue by HebelHuber** [Tifaifai/mosquitto#6]
Hi,

that repo looks awesome!
Can yout tell me how the bridging behaves in case of a full circle?
Like so: A->B->C->D->A
or even like so:
```
A ---- B
| \    |
|   \  |
|     \|
C ---- D
```

I'd like to know if it's possible to find compiled binaries somewhere for download?
I'm trying to run it on windows but the build process looks quite daring to me. 

I'd try to build it if there's no other way.
Thanks

**Comment by HebelHuber** [comment]
I found build instructions here
https://github.com/bapowell/bapowell.github.io/wiki/Mosquitto-Build-Notes-(Windows-Visual-Studio)-Sept-14-2018

Should this work if use your source instead?

**Comment by Tifaifai** [comment]
Hello,
I use Linux (Ubuntu Distribution ;) )
In case of a full circle, it's crashed ;)
Bridge client or admin mosquitto broker must know how run mosquitto ;) infinite loop of message
THX
